version: '3'

services:
  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
  ghost:
    container_name: ghost
    image: ghost:3-alpine
    restart: always
    depends_on:
       - mysql
    volumes:
      - ./ghost:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      TZ: 'Asia/Tokyo'
  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:1
    depends_on:
       - ghost
    ports:
       - '80:80'
       - '443:443'
    restart: always
    volumes:
       - ./ssl:/var/lib/https-portal
    environment:
      DOMAINS: '${DOMAIN} -> http://ghost/'
      STAGE: ${ENV}
      TZ: 'Asia/Tokyo'
